<?php


use Illuminate\Database\Seeder;
use ChuJC\Admin\Models\AdminUser;
use ChuJC\Admin\Models\AdminRole;
use ChuJC\Admin\Models\AdminMenu;
use ChuJC\Admin\Models\AdminDictDatum;
use ChuJC\Admin\Models\AdminDictType;
use Illuminate\Support\Facades\Hash;

class AdminDatabaseSeeder extends Seeder
{

    private $dictTypes = [
        [
            'dict_name' => '系统公共状态',
            'dict_type' => 'system_common_status',
            'is_system' => 1,
            'status' => 1,
            'remark' => '系统状态列表'
        ],
        [
            'dict_name' => '系统登录状态',
            'dict_type' => 'system_login_status',
            'is_system' => 1,
            'status' => 1,
            'remark' => '系统登录状态列表'
        ],
        [
            'dict_name' => '是否系统内置',
            'dict_type' => 'system_built_in',
            'is_system' => 1,
            'status' => 1,
            'remark' => '是否系统内置列表'
        ],
        [
            'dict_name' => '菜单显示状态',
            'dict_type' => 'system_menu_show',
            'is_system' => 1,
            'status' => 1,
            'remark' => '菜单显示状态'
        ],
    ];

    private $dictData = [
        [
            'dict_label' => '显示',
            'dict_value' => '1',
            'dict_type' => 'system_menu_show',
            'dict_order' => 1,
            'is_default' => 1,
            'is_system' => 0,
            'status' => 0,
            'remark' => '显示菜单',
        ],
        [
            'dict_label' => '隐藏',
            'dict_value' => '0',
            'dict_type' => 'system_menu_show',
            'dict_order' => 2,
            'is_default' => 0,
            'is_system' => 0,
            'status' => 0,
            'remark' => '隐藏菜单',
        ],
        [
            'dict_label' => '正常',
            'dict_value' => '1',
            'dict_type' => 'system_common_status',
            'dict_order' => 1,
            'is_default' => 1,
            'is_system' => 0,
            'status' => 1,
            'remark' => '正常状态',
        ],
        [
            'dict_label' => '停用',
            'dict_value' => '0',
            'dict_type' => 'system_common_status',
            'dict_order' => 2,
            'is_default' => 0,
            'is_system' => 0,
            'status' => 1,
            'remark' => '停用状态',
        ],
        [
            'dict_label' => '是',
            'dict_value' => '1',
            'dict_type' => 'system_built_in',
            'dict_order' => 1,
            'is_default' => 1,
            'is_system' => 0,
            'status' => 0,
            'remark' => '系统内置是',
        ],
        [
            'dict_label' => '否',
            'dict_value' => '0',
            'dict_type' => 'system_built_in',
            'dict_order' => 2,
            'is_default' => 0,
            'is_system' => 0,
            'status' => 0,
            'remark' => '系统内置否',
        ],
        [
            'dict_label' => '成功',
            'dict_value' => '1',
            'dict_type' => 'system_login_status',
            'dict_order' => 1,
            'is_default' => 0,
            'is_system' => 0,
            'status' => 0,
            'remark' => '成功状态',
        ],
        [
            'dict_label' => '失败',
            'dict_value' => '0',
            'dict_type' => 'system_login_status',
            'dict_order' => 2,
            'is_default' => 0,
            'is_system' => 0,
            'status' => 0,
            'remark' => '失败状态'
        ],
    ];

    private $menus = [
        [
            'menu_id' => 1,
            'menu_name' => '系统管理',
            'parent_id' => 0,
            'order' => 1,
            'path' => 'system',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 1,
            'is_visible' => 1,
            'permission' => '',
            'icon' => 'system',
            'remark' => '系统管理目录',
        ],
        [
            'menu_id' => 100,
            'menu_name' => '管理员管理',
            'parent_id' => 1,
            'order' => 1,
            'path' => 'user',
            'component' => 'system/user/index',
            'is_link' => 0,
            'menu_type' => 1,
            'is_visible' => 1,
            'permission' => 'admin.users.index',
            'icon' => 'user',
            'remark' => '管理员管理菜单',
        ],
        [
            'menu_id' => 101,
            'menu_name' => '角色管理',
            'parent_id' => 1,
            'order' => 2,
            'path' => 'role',
            'component' => 'system/role/index',
            'is_link' => 0,
            'menu_type' => 1,
            'is_visible' => 1,
            'permission' => 'admin.roles.index',
            'icon' => 'peoples',
            'remark' => '角色管理菜单',
        ],
        [
            'menu_id' => 102,
            'menu_name' => '菜单管理',
            'parent_id' => 1,
            'order' => 3,
            'path' => 'menu',
            'component' => 'system/menu/index',
            'is_link' => 0,
            'menu_type' => 1,
            'is_visible' => 1,
            'permission' => 'admin.menus.index',
            'icon' => 'tree-table',
            'remark' => '菜单管理菜单',
        ],
        [
            'menu_id' => 103,
            'menu_name' => '字典管理',
            'parent_id' => 1,
            'order' => 6,
            'path' => 'dict',
            'component' => 'system/dict/index',
            'is_link' => 0,
            'menu_type' => 1,
            'is_visible' => 1,
            'permission' => 'admin.dict.types.index',
            'icon' => 'dict',
            'remark' => '字典管理菜单',
        ],
        [
            'menu_id' => 104,
            'menu_name' => '参数设置',
            'parent_id' => 1,
            'order' => 7,
            'path' => 'config',
            'component' => 'system/config/index',
            'is_link' => 0,
            'menu_type' => 1,
            'is_visible' => 1,
            'permission' => 'admin.configs.index',
            'icon' => 'edit',
            'remark' => '参数设置菜单',
        ],
        [
            'menu_id' => 105,
            'menu_name' => '登录日志',
            'parent_id' => 1,
            'order' => 9,
            'path' => 'logininfor',
            'component' => 'system/log/login',
            'is_link' => 0,
            'menu_type' => 1,
            'is_visible' => 1,
            'permission' => 'admin.logs.login.index',
            'icon' => 'log',
            'remark' => '登录日志菜单',
        ],
        [
            'menu_id' => 106,
            'menu_name' => '操作日志',
            'parent_id' => 1,
            'order' => 10,
            'path' => 'operlog',
            'component' => 'system/log/operation',
            'is_link' => 0,
            'menu_type' => 1,
            'is_visible' => 1,
            'permission' => 'admin.logs.operation.index',
            'icon' => 'form',
            'remark' => '操作日志菜单',
        ],
        [
            'menu_id' => 1001,
            'menu_name' => '用户详情',
            'parent_id' => 100,
            'order' => 1,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.users.show',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1002,
            'menu_name' => '用户新增',
            'parent_id' => 100,
            'order' => 2,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.users.store',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1003,
            'menu_name' => '用户修改',
            'parent_id' => 100,
            'order' => 3,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.users.update',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1004,
            'menu_name' => '用户删除',
            'parent_id' => 100,
            'order' => 4,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.users.destroy',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1005,
            'menu_name' => '重置密码',
            'parent_id' => 100,
            'order' => 5,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.users.update',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1006,
            'menu_name' => '角色详情',
            'parent_id' => 101,
            'order' => 1,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.roles.show',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1007,
            'menu_name' => '角色新增',
            'parent_id' => 101,
            'order' => 2,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.roles.store',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1008,
            'menu_name' => '角色修改',
            'parent_id' => 101,
            'order' => 3,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.roles.update',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1009,
            'menu_name' => '角色删除',
            'parent_id' => 101,
            'order' => 4,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.roles.destroy',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1010,
            'menu_name' => '菜单查询',
            'parent_id' => 102,
            'order' => 1,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.menus.show',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1011,
            'menu_name' => '菜单新增',
            'parent_id' => 102,
            'order' => 2,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.menus.store',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1012,
            'menu_name' => '菜单修改',
            'parent_id' => 102,
            'order' => 3,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.menus.update',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1013,
            'menu_name' => '菜单删除',
            'parent_id' => 102,
            'order' => 4,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.menus.destroy',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1014,
            'menu_name' => '字典查询',
            'parent_id' => 103,
            'order' => 1,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.dict.types.show',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1015,
            'menu_name' => '字典新增',
            'parent_id' => 103,
            'order' => 2,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.dict.types.store',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1016,
            'menu_name' => '字典修改',
            'parent_id' => 103,
            'order' => 3,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.dict.types.update',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1017,
            'menu_name' => '字典删除',
            'parent_id' => 103,
            'order' => 4,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.dict.types.destroy',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1018,
            'menu_name' => '参数查询',
            'parent_id' => 104,
            'order' => 1,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.dict.data.show',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1019,
            'menu_name' => '参数新增',
            'parent_id' => 104,
            'order' => 2,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.dict.data.store',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1020,
            'menu_name' => '参数修改',
            'parent_id' => 104,
            'order' => 3,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.dict.data.update',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1021,
            'menu_name' => '参数删除',
            'parent_id' => 104,
            'order' => 4,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.dict.data.destroy',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1022,
            'menu_name' => '登录查询',
            'parent_id' => 105,
            'order' => 1,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.logs.login.show',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1023,
            'menu_name' => '登录删除',
            'parent_id' => 105,
            'order' => 2,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.logs.login.destroy',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1024,
            'menu_name' => '日志导出',
            'parent_id' => 105,
            'order' => 3,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.logs.login.export',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1025,
            'menu_name' => '操作查询',
            'parent_id' => 106,
            'order' => 1,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.logs.operation.show',
            'icon' => '',
            'remark' => '',
        ],
        [
            'menu_id' => 1026,
            'menu_name' => '操作删除',
            'parent_id' => 106,
            'order' => 2,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.logs.operation.destroy',
            'icon' => '',
            'remark' => ''
        ],
        [
            'menu_id' => 1027,
            'menu_name' => '日志导出',
            'parent_id' => 106,
            'order' => 4,
            'path' => '',
            'component' => '',
            'is_link' => 0,
            'menu_type' => 2,
            'is_visible' => 1,
            'permission' => 'admin.logs.operation.export',
            'icon' => '',
            'remark' => ''
        ],
    ];

    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        AdminUser::truncate();
        $adminUser = AdminUser::create([
            'username' => 'admin',
            'nickname' => '超级管理员',
            'password' => Hash::make('123456'),
            'status' => 1
        ]);

        AdminRole::truncate();
        $adminRole = AdminRole::create([
            'role_name' => '管理员',
            'role_key' => 'administrator',
            'status' => 1,
            'remark' => '超级管理员角色',
        ]);

        $adminUser->roles()->save($adminRole);

        AdminMenu::truncate();

        AdminMenu::insert($this->menus);

        $adminRole->menus()->saveMany(AdminMenu::get());

        AdminDictType::truncate();
        AdminDictType::insert($this->dictTypes);
        AdminDictDatum::truncate();
        AdminDictDatum::insert($this->dictData);
    }


}
